<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * BiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiensRepository extends \Doctrine\ORM\EntityRepository
{
	 public function findBien($IdLocalite, $Prix, $IdType)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $u = $qb->select('b', 't', 'l', 'i')
        ->from('AkinaImmobilierBundle:Biens', 'b')
        ->leftJoin('b.IdLocalite', 'l')
        ->leftJoin('b.IdType', 't')
        ->leftJoin('b.IdImage', 'i')
        ->where('l = :IdLocalite')
        ->andWhere('t = :IdType')
        ->andWhere('b.Prix > :Prix')
        ->setParameters(array(
            ':IdLocalite' => $IdLocalite,
            ':Prix' => $Prix,
            ':IdType' => $IdType,
            ))->getQuery();

        return $u->getResult();
    }
}
